// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     alert.avsc
 *     candidate.avsc
 *     cutout.avsc
 *     fp_hist.avsc
 *     prv_candidate.avsc
 */
package schema

import (
	"io"

	"github.com/actgardner/gogen-avro/vm/types"
	"github.com/actgardner/gogen-avro/vm"
)

func writeArrayFp_hist(r []*Fp_hist, w io.Writer) error {
	err := vm.WriteLong(int64(len(r)),w)
	if err != nil || len(r) == 0 {
		return err
	}
	for _, e := range r {
		err = writeFp_hist(e, w)
		if err != nil {
			return err
		}
	}
	return vm.WriteLong(0,w)
}



type ArrayFp_histWrapper []*Fp_hist

func (_ *ArrayFp_histWrapper) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *ArrayFp_histWrapper) SetInt(v int32) { panic("Unsupported operation") }
func (_ *ArrayFp_histWrapper) SetLong(v int64) { panic("Unsupported operation") }
func (_ *ArrayFp_histWrapper) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *ArrayFp_histWrapper) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *ArrayFp_histWrapper) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *ArrayFp_histWrapper) SetString(v string) { panic("Unsupported operation") }
func (_ *ArrayFp_histWrapper) SetUnionElem(v int64) { panic("Unsupported operation") }
func (_ *ArrayFp_histWrapper) Get(i int) types.Field { panic("Unsupported operation") }
func (_ *ArrayFp_histWrapper) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *ArrayFp_histWrapper) Finalize() { }
func (_ *ArrayFp_histWrapper) SetDefault(i int) { panic("Unsupported operation") }
func (r *ArrayFp_histWrapper) AppendArray() types.Field {
	var v *Fp_hist
	
	v = NewFp_hist()

 	
	*r = append(*r, v)
        
        return (*r)[len(*r)-1]
        
}
