// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     alert.avsc
 *     candidate.avsc
 *     cutout.avsc
 *     fp_hist.avsc
 *     prv_candidate.avsc
 */
package schema

import (
	"io"

	"github.com/actgardner/gogen-avro/container"
	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/compiler"
)

func NewFp_histWriter(writer io.Writer, codec container.Codec, recordsPerBlock int64) (*container.Writer, error) {
	str := NewFp_hist()
	return container.NewWriter(writer, codec, recordsPerBlock, str.Schema())
}

// container reader
type Fp_histReader struct {
	r io.Reader
	p *vm.Program
}

func NewFp_histReader(r io.Reader) (*Fp_histReader, error){
	containerReader, err := container.NewReader(r)
	if err != nil {
		return nil, err
	}

	t := NewFp_hist()
	deser, err := compiler.CompileSchemaBytes([]byte(containerReader.AvroContainerSchema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	return &Fp_histReader {
		r: containerReader,
		p: deser,
	}, nil
}

func (r Fp_histReader) Read() (*Fp_hist, error) {
	t := NewFp_hist()
        err := vm.Eval(r.r, r.p, t)
	return t, err
}
