// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     alert.avsc
 *     candidate.avsc
 *     cutout.avsc
 *     fp_hist.avsc
 *     prv_candidate.avsc
 */
package schema

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type UnionNullArrayFp_histTypeEnum int
const (

	 UnionNullArrayFp_histTypeEnumNull UnionNullArrayFp_histTypeEnum = 0

	 UnionNullArrayFp_histTypeEnumArrayFp_hist UnionNullArrayFp_histTypeEnum = 1

)

type UnionNullArrayFp_hist struct {

	Null *types.NullVal

	ArrayFp_hist []*Fp_hist

	UnionType UnionNullArrayFp_histTypeEnum
}

func writeUnionNullArrayFp_hist(r *UnionNullArrayFp_hist, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case UnionNullArrayFp_histTypeEnumNull:
		return vm.WriteNull(r.Null, w)
        
	case UnionNullArrayFp_histTypeEnumArrayFp_hist:
		return writeArrayFp_hist(r.ArrayFp_hist, w)
        
	}
	return fmt.Errorf("invalid value for *UnionNullArrayFp_hist")
}

func NewUnionNullArrayFp_hist() *UnionNullArrayFp_hist {
	return &UnionNullArrayFp_hist{}
}

func (_ *UnionNullArrayFp_hist) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *UnionNullArrayFp_hist) SetInt(v int32) { panic("Unsupported operation") }
func (_ *UnionNullArrayFp_hist) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *UnionNullArrayFp_hist) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullArrayFp_hist) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *UnionNullArrayFp_hist) SetString(v string) { panic("Unsupported operation") }
func (r *UnionNullArrayFp_hist) SetLong(v int64) { 
	r.UnionType = (UnionNullArrayFp_histTypeEnum)(v)
}
func (r *UnionNullArrayFp_hist) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
		return r.Null
		
	
	case 1:
		
		r.ArrayFp_hist = make([]*Fp_hist, 0)
		
		
		return (*ArrayFp_histWrapper)(&r.ArrayFp_hist)
		
	
	}
	panic("Unknown field index")
}
func (_ *UnionNullArrayFp_hist) SetDefault(i int) { panic("Unsupported operation") }
func (_ *UnionNullArrayFp_hist) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionNullArrayFp_hist) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *UnionNullArrayFp_hist) Finalize()  { }
