// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     alert.avsc
 *     candidate.avsc
 *     cutout.avsc
 *     prv_candidate.avsc
 */
package schema

import (
	"io"

	"github.com/actgardner/gogen-avro/container"
	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/compiler"
)

func NewPrv_candidateWriter(writer io.Writer, codec container.Codec, recordsPerBlock int64) (*container.Writer, error) {
	str := NewPrv_candidate()
	return container.NewWriter(writer, codec, recordsPerBlock, str.Schema())
}

// container reader
type Prv_candidateReader struct {
	r io.Reader
	p *vm.Program
}

func NewPrv_candidateReader(r io.Reader) (*Prv_candidateReader, error){
	containerReader, err := container.NewReader(r)
	if err != nil {
		return nil, err
	}

	t := NewPrv_candidate()
	deser, err := compiler.CompileSchemaBytes([]byte(containerReader.AvroContainerSchema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	return &Prv_candidateReader {
		r: containerReader,
		p: deser,
	}, nil
}

func (r Prv_candidateReader) Read() (*Prv_candidate, error) {
	t := NewPrv_candidate()
        err := vm.Eval(r.r, r.p, t)
	return t, err
}
